### ISSUE TITLE
Player Name Length and Signs

### ISSUE THREAD

**Issue by Ironinstrumentals** [DosMike/Lockette-Sponge-#3]
So uh, not really sure if this counts as an issue, but Playernames can contain more characters than what will fit on one line of a sign, thus, making them unable to access any containers they have locked.

**Comment by DosMike** [comment]
access data are stored as uuids, not by names. it just displays names because that’s more convenient to read. 
https://github.com/DosMike/Lockette-Sponge-/blob/98a5c6409229530ce22f8fccb104aeb0e3046fab/src/de/dosmike/sponge/lockette/Lock.java#L31 <- This method checks access and that only takes uuids
If you're having any issues with access it's something different. you can try and use the //nbt tool in Mike's ToolBox to analyse the signs.
